Vagrant.configure("2") do |config|
  config.vm.define "salt" do |salt|
    salt.vm.box = "ubuntu/trusty64"
    salt.vm.hostname = "salt"
    salt.vm.network "private_network", ip: "192.168.5.10"
    salt.vm.provision :shell, path: "bootstrap-salt.sh"
  end
  config.vm.define "devminion" do |devminion|
    devminion.vm.box = "ubuntu/trusty64"
    devminion.vm.hostname = "devminion"
    devminion.vm.network "private_network", ip: "192.168.5.11"
    devminion.vm.provision :shell, path: "bootstrap-devminion.sh"
  end
  config.vm.define "prodminion" do |prodminion|
    prodminion.vm.box = "ubuntu/trusty64"
    prodminion.vm.hostname = "prodminion"
    prodminion.vm.network "private_network", ip: "192.168.5.12"
    prodminion.vm.provision :shell, path: "bootstrap-prodminion.sh"
  end
  config.vm.post_up_message = "Welcome to the DevOps Library SaltStack demo.  Use the command 'vagrant ssh salt' to access the salt-master or 'vagrant ssh devminion' to access the devminion, or lastly 'vagrant ssh prodminion' to access the prodminion."
end