Vagrant.configure(2) do |config|
  config.vm.box = "lmayorga1980/windows-2012r2"
  config.vm.communicator = "winrm"
  config.vm.network "forwarded_port", guest: 3389, host: 53389
  config.vm.provision :shell, inline: "puppet module install --force rismoney/chocolatey"
  config.vm.provision "puppet"
end
