Vagrant.configure("2") do |config|
  config.vm.define "jenkins" do |salt|
    salt.vm.box = "ubuntu/trusty64"
    salt.vm.hostname = "jenkins"
    salt.vm.network "private_network", ip: "192.168.5.12"
    salt.vm.provision :shell, path: "bootstrap.sh"
  end
  config.vm.post_up_message = "Welcome to the DevOps Library Jenkins demo.  Use the command 'vagrant ssh' to SSH into Jenkins, or visit http://192.168.5.12 to see the Jenkins WebUI!"
end